Added AF Connect consent logging
MagnumOpuses/af-portability pull request #48
Opened 2021-04-29 07:37 UTC by mobimation-gunnar

Logging done of JSON structure including clear text
declaration of given consent.

(Thanks for sending a pull request! Please make sure you click the link above to view the [contribution guidelines](CONTRIBUTING.md), then fill out the blanks below.)

---

Consent logging keeps a log of events of AF User Profile data transfer occurring as part
of the AF Connect service. The user has given consent of selected portions of his/her
profile (CV) data be shared with an external job advertising entity. The log entry
details user, what data was shared, at what time, session id, etc.
A log entry consists of a JSON structure containing an embedded clear text declaration.  

...

Will close Jira task ONCE-50 "Map ASP profile to HROpen profileId" and ONCE-51 "Logging" once accepted.

...

**Any relevant logs, error output, etc?**

The log entry structure is according to this template:

{
  "application": {
    "name": "af-portability",
    "class": "se.arbetsformedlingen.matchning.portability.rest.StoreApi"
  },
  "event": {
    "action": "grant"
  },
  "consent": {
    "personalNumber": "197309069289",
    "profileId": "94222",
    "purpose": "..."
    "consent": "..."
  },
  "@timestamp": "2020-07-03 12:30:00.123",
  "log": {
    "level": "INFO"
  },
  "session": {
    "id": "86b7818b-1234-1234-1234-8ab31b444d40"
  }
}

where "consent" holds a clear text consent declaration.

Typical "consent" clear text portion:
---
Jag, Nina Greger (1973-09-06-9289) har vid tidpunkten 2021-04-29T07:35:51.134Z givit följande medgivande
till Dummy att ta emot arbets-profil-data (CV) med profil-id 93860 från Arbetsförmedlingen,
för användning som del av arbets-ansökan.
             MEDGIVANDE
Dummy får endast använda uppgifterna i följande syfte:
   • Ansökan till roll 'Tandl�kare' på Landstinget V�stmanland

   • Jag ger mitt medgivande till att Arbetsförmedlingen under ett tillfälle får hantera och överföra dessa
     uppgifter till Dummy.
   • Jag samtycker till att denna process häver sekretessen för de uppgifter jag väljer att dela
     med Dummy.
   • Jag har granskat uppgifterna och bekräftar att inga oönskade uppgifter ingår
     i överföringen till Dummy.
   • Jag har läst och förstår följande bilaga: "Behandling av dina personuppgifter":

   Behandling av dina personuppgifter

   • Den här tjänsten gör det möjligt att skicka ditt valda CV till Dummy.
     Arbetsförmedlingen ansvarar inte för uppgifterna när de har levererats.
   • Arbetsförmedlingen kommer att lagra all samtyckeinformation som en del av deras
     processer, inklusive vilket jobb du har ansökt om och när. Den loggade informationen
     betraktas som av allmänt intresse och kan begäras ut till allmänheten på begäran.
   • Klicka HÄR för att lära dig mer om hur Arbetsförmedlingen behandlar dina uppgifter.
   • Dummy är skyldigt att använda dina uppgifter enligt EU:s allmänna dataskyddsförordning.
   • Efter att uppgifterna har levererats till Dummy kan Arbetsförmedlingen inte verifiera
         ◦ hur eller var informationen kommer att lagras;
         ◦ om dina uppgifter kommer att skickas till andra parter;
         ◦ om uppgifterna kommer att användas för ett annat syfte än en som anges ovan; eller
         ◦ som kommer att kunna komma åt uppgifterna.
   • Om du känner att dina uppgifter missbrukas på något sätt, vänligen kontakta
    "Datainspektionen" => (https://www.datainspektionen.se)
-----
See StoreAPI.java for details.
...

**Any other comments?**

...

**Where has this been tested?**
 - Macbook Pro 15, macOS Catalina 10.15.7
 - Chrome browser 90.0.4430.93 (Official Build) (x86_64)
 - IntelliJ IDEA IntelliJ IDEA 2021.1 (Ultimate Edition) Build #IU-211.6693.111

2021-04-29 12:12 UTC, ixuz commented on pom.xml
> +            <groupId>org.mockito</groupId>
Is this dependency actually used?

2021-04-29 12:13 UTC, ixuz commented on pom.xml
> +            <artifactId>testng</artifactId>
Is this dependency actually used?

2021-04-29 12:18 UTC, ixuz requested changes

2021-04-29 12:18 UTC, ixuz commented on pom.xml
> +            <artifactId>junit</artifactId>
This is a duplicate dependency, remove this duplication

2021-04-29 12:18 UTC, ixuz commented on pom.xml
> +            <groupId>org.mockito</groupId>
Is this dependency actually used?

2021-04-29 12:18 UTC, ixuz commented on pom.xml
> +            <artifactId>testng</artifactId>
Is this dependency actually used?

2021-04-29 12:18 UTC, ixuz commented on src/main/java/se/arbetsformedlingen/matchning/portability/builder/CandidatePersonTypeBuilder.java
> +        setLegalId(new IdentifierTypeBuilder().setValue(personUppgifter.getPersonnummer()).build());
Make sure that this personal number is removed from the CV before it's written to Redis.
See the file "StoreApi.java", line: `results = this.storeValueToRedis(body);`

2021-04-29 12:18 UTC, ixuz commented on src/main/java/se/arbetsformedlingen/matchning/portability/rest/StoreApi.java
> +        // Create JSON log structure
Move the JsonNode creation into a separate function.

2021-04-30 12:47 UTC, ixuz commented on src/main/java/se/arbetsformedlingen/matchning/portability/builder/CandidatePersonTypeBuilder.java
> +        setLegalId(new IdentifierTypeBuilder().setValue(personUppgifter.getPersonnummer()).build());
This was resolved by commit https://github.com/MagnumOpuses/af-portability/pull/48/commits/c39e43710d248449a61442f12bfd2db19630bd14

2021-04-30 16:11 UTC, mobimation-gunnar commented on pom.xml
> +            <groupId>org.mockito</groupId>
I removed what seems like unneeded dependencies.
Verified the project builds properly.

2021-04-30 16:34 UTC, mobimation-gunnar reviewed
Please check if you see any outstanding issues now.

2021-04-30 16:34 UTC, mobimation-gunnar commented on src/main/java/se/arbetsformedlingen/matchning/portability/rest/StoreApi.java
> +        // Create JSON log structure
Looks to me this is resolved.

2021-04-30 16:34 UTC, mobimation-gunnar commented on src/main/java/se/arbetsformedlingen/matchning/portability/rest/StoreApi.java
> +        // Create JSON log structure
From what I see this is no longer an issue, please check.

2021-05-03 06:11 UTC, ixuz requested changes

2021-05-03 06:11 UTC, ixuz commented on pom.xml
> +            <artifactId>testng</artifactId>
This dependency is still in the code, remove it please.

2021-05-03 06:11 UTC, ixuz commented on pom.xml
> +        </dependency>
Don't remove the <build> plugin.

2021-05-03 07:31 UTC, mobimation-gunnar commented on pom.xml
> +        </dependency>
Removed testng and junit dependencies, no complaints. Restored <build> section.

2021-05-03 08:05 UTC, ixuz approved these changes

2021-05-03 08:43 UTC, merged